server:
  port: 8091

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: feign
#未测试
feign:
   hytrix:
    enabled: true

